INSERT INTO contents (id, title, type, overview, poster_path, rating, year, genres, streaming) VALUES
(1, 'O Poderoso Chefão', 'movie', 'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.', 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 9.2, 1972, '["Crime", "Drama"]', '["Netflix", "Prime Video"]'),
(2, 'Breaking Bad', 'series', 'Ao saber que tem câncer, um professor passa a fabricar metanfetamina pelo futuro da família, mudando o destino de todos.', 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg', 9.5, 2008, '["Drama", "Crime"]', '["Netflix"]'),
(3, 'Interestelar', 'movie', 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial.', 'https://image.tmdb.org/t/p/w500/gEU2QniL6E8ahDaX06e8q288UL.jpg', 8.6, 2014, '["Ficção Científica", "Drama", "Aventura"]', '["HBO Max", "Prime Video"]'),
(4, 'Stranger Things', 'series', 'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.', 'https://image.tmdb.org/t/p/w500/uOVpJ62Q8f6t7yL023J3b5h9W6.jpg', 8.7, 2016, '["Ficção Científica", "Terror", "Drama"]', '["Netflix"]'),
(5, 'A Origem', 'movie', 'Dom Cobb é um ladrão com a rara habilidade de roubar segredos do inconsciente, obtidos durante o estado de sono.', 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', 8.8, 2010, '["Ação", "Ficção Científica", "Aventura"]', '["HBO Max"]'),
(6, 'The Boys', 'series', 'A Terra é habitada por super-heróis que são inspiração para a humanidade. Porém, a maioria deles abusa de seus poderes ao invés de usá-los para o bem.', 'https://image.tmdb.org/t/p/w500/stTEycfG9928iv8tDAI5VXVMSCM.jpg', 8.5, 2019, '["Ação", "Ficção Científica", "Comédia"]', '["Prime Video"]'),
(7, 'Cidade de Deus', 'movie', 'Buscapé é um jovem pobre, negro e muito sensível, que cresce em um universo de muita violência. Ele vive na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio.', 'https://image.tmdb.org/t/p/w500/t9O11L9a75r0WfB66Y0eZ6b0w6.jpg', 8.4, 2002, '["Drama", "Crime"]', '["Globoplay", "Netflix"]'),
(8, 'Game of Thrones', 'series', 'Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, sete nobres famílias lutam pelo controle da mítica terra de Westeros.', 'https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', 8.4, 2011, '["Fantasia", "Drama", "Aventura"]', '["HBO Max"]'),
(9, 'Matrix', 'movie', 'Um jovem programador é atormentado por estranhos pesadelos nos quais sempre está conectado por cabos a um imenso sistema de computadores do futuro.', 'https://image.tmdb.org/t/p/w500/lDqMDI3xpbB9UprweTBcdnZUBFc.jpg', 8.7, 1999, '["Ação", "Ficção Científica"]', '["HBO Max", "Prime Video"]'),
(10, 'Friends', 'series', 'Seis jovens são unidos por laços familiares, românticos e, principalmente, de amizade, enquanto tentam vingar em Nova York.', 'https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg', 8.5, 1994, '["Comédia", "Romance"]', '["HBO Max"]');
